version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace          # mount project into container
    working_dir: /workspace
    tty: true
